### ISSUE TITLE
problem after upgrading to 7.2

### ISSUE THREAD

**Issue by DervilRus** [007revad/Synology_enable_M2_volume#10]
Hello. I have a problem after upgrading to 7.2. Help me please. I have DS 920+. Today I updated to 7.2 After the reboot, I got a non-working SSD. Synology in NVME properties writes an unsupported device. Online assembly/restoration of the volume fails. Is there any chance that your script will help in my data recovery problem?

**Comment by DervilRus** [comment]
![syno1](https://user-images.githubusercontent.com/84242788/229271550-b1ccc917-ff65-4d66-b915-92761277a0eb.jpg)
![syno2](https://user-images.githubusercontent.com/84242788/229271533-e5661909-128f-4b58-914a-94321bfd3a5a.jpg)
![syno3](https://user-images.githubusercontent.com/84242788/229271616-100d3a85-298c-4f1b-8bae-34caba0489f2.jpg)

Please take a look.
What can be done in this situation

**Comment by 007revad** [comment]
Running the script wont make it worse. If it doesn't help you can run the script again with the -- restore option to undo the change the script made.

Otherwise I'd suggest connecting the M.2 drive to a Linux computer (or boot a PC from a Linux boot disk) then mount the data partition and backup your data.

**Comment by DervilRus** [comment]
Thank you very much for the answer. I solved the problem. Or rather, you solved my problem, but with another script, https://github.com/007revad/Synology_HDD_db, it helped!!!!!!!!

**Comment by aferende** [comment]
Is the data in the storage pool/volume intact?  All recovered?

**Comment by DervilRus** [comment]
> Is the data in the storage pool/volume intact? All recovered?

Everything is fine, the syno_hdd_db.sh script returned my status as of the update to 7.2

**Comment by DervilRus** [comment]
I have an idea. Maybe it makes sense to add to this script the addition of nvme to the database of compatible devices? I think right now, many will begin to face my problem.

**Comment by aferende** [comment]
I think it makes sense too. Most people who buy M2 for NAS are not using the official Synology ones.
At least a message in the M2 script warning to recommend a vision of the HDD update script could be very useful, or a clear alert in the readme.md on the github homepage

**Comment by 007revad** [comment]
Good idea.

The syno_hdd_db.sh script would have enabled support_m2_volume, as well as adding your drives to the compatibility database.

**Comment by 007revad** [comment]
I've had a think about the suggestions and I can't add the NVMe drives to the drive compatibility db files in the syno_hdd_db.sh script because the db files get replaced when doing a DSM update.

I'll add a warning on the readme and show the warning in the syno_create_m2_volume.sh script that shows when it runs.

**Comment by 007revad** [comment]
I've added a warning on the Synology_M2_volume readme and updated [Synology_M2_volume v1.2.12](https://github.com/007revad/Synology_M2_volume/releases/tag/v1.2.12)
