### ISSUE TITLE
Feature request: telemetry

### ISSUE THREAD

**Issue by aioue** [007revad/Synology_enable_M2_volume#105]
Opt-in switch to send all functioning disks to you and have them displayed somewhere public for the community to see compatible drives.

Would be interesting to see what hardware people are running.

**Comment by 007revad** [comment]
Interesting idea.

I'd probably also make it send the Synology model, DSM version and location of the drives (internal, expansion box or M.2 card).

I wonder if people would be annoyed if I made it the default with an opt-out switch.

**Comment by huksley** [comment]
> I wonder if people would be annoyed if I made it the default with an opt-out switch.
yes

**Comment by 007revad** [comment]
A lot of the feedback in the issues mention the NVMe drives they are using. I never bothered to add the NVMe models to the compatibility list because the script should work with any NVMe drive.

To add telemetry I'd need a webserver with an API that could receive and collate the details... which seems like a really big job.
