### ISSUE TITLE
Clarify whether or not to use --noreboot on scheduled task

### ISSUE THREAD

**Issue by catch-404** [007revad/Synology_enable_M2_volume#193]
Hi, I'm creating this simply because I'm not sure whether or not to use the `--noreboot` flag when scheduling this script on shutdown. Maybe it doesn't matter, but if you could clarify that that'd be great. :)

Cheers

**Comment by 007revad** [comment]
That's actually a good question. It's been 11 months since I added the --noreboot option so I had to check the script to see what it does. 

The current script version: 
- Without the -n or --noreboot option the script will ask if you want to reboot now, and if you don't type yes within 10 seconds the script exits. 
- With the -n or --noreboot option the script will skip asking if you want to reboot and just exit.

So the -n or --noreboot option is kind of redundant, but it does save 10 seconds.

**Comment by catch-404** [comment]
Cool, thank you!
