### ISSUE TITLE
not working DVA version 7.2

### ISSUE THREAD

**Issue by ITNetSystem** [007revad/Synology_enable_M2_volume#52]
I can only create an ssd cache, the pool does not allow me to create, writes that disks are not supported. Can you add DVA3219 support? I tried the syno_create_m2_volume script.sh and it successfully creates a resource pool, but I would like to manage it via DSM.

**Comment by 007revad** [comment]
syno_enable_m2_volume. should work on a DVA3219 with DSM 7.2

**Comment by ITNetSystem** [comment]
Just the same syno_create_m2_volume works. He builds an array and then I do an online build in DSM. The syno_enable_m2_volume script works, but when trying to create a pool, it writes that there are no suitable disks. I tried the script for adding disks to the database, it didn't help.

**Comment by ITNetSystem** [comment]
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/135026873/c0a8030e-9da4-4a31-89d9-aa531652e749)

**Comment by 007revad** [comment]
Did you reboot the DVA3219 after running the Synology_HDD_db script?

**Comment by ITNetSystem** [comment]
Yes, of course I did. For some reason, I also have a problem that hdd disks writes that the firmware is not recognized, I tried to install offline updating of the disk database, but still does not recognize it, everything was fine before.
![image](https://github.com/007revad/Synology_enable_M2_volume/assets/135026873/56fdf718-967e-40aa-a51a-d7314edffc57)

**Comment by 007revad** [comment]
I can't read the text in your screenshots. But I can see that the M.2 drives are shown as:
- Drive M.2 1-1
- Drive M.2 2-1

I'm not sure why they are "1-1" and "2-1" instead of just 1 and 2.

I've just looked at the DVA3219 specs and it doesn't have any M.2 slots or a PCIe slot for an M.2 card. it only supports 2.5 inch SATA SSDs. And DSM already supports creating storage pools and volumes on 2.5 inch SATA SSDs.

Run both scripts with the --restore option to undo what the changes they've made. Then reboot the DVA.
