### ISSUE TITLE
Make it possible for USB-Disks

### ISSUE THREAD

**Issue by DenisMtfl** [007revad/Synology_enable_M2_volume#58]
Since DSM 7.1 there is no Port configs in synoinfo.conf for bringing the USB-Disks to a Volume.
Do you have an idea to make it possible anymore?

**Comment by 007revad** [comment]
> Since DSM 7.1 there is no Port configs in synoinfo.conf for bringing the USB-Disks to a Volume.
> Do you have an idea to make it possible anymore?

Are you saying that DSM 7.0 let you create a volume using USB disks?

**Comment by 007revad** [comment]
@DenisMtfl 

Just because the usbportcfg key is not in synoinfo.conf by default any more does not mean you can't add it. In some cases DSM will check if the key exists in synoinfo.conf and then use a default setting if the key doesn't exist.

The synosetkeyvalue command will add the key+value if it doesn't exist, or change the value if the key does exist. 
Note: Using synosetkeyvalue to set a key in **/etc.defaults/synoinfo.conf** also sets the same key in **/etc/synoinfo.conf** (saves you having to edit both files by hand).

This should work:
```
sudo -i
synosetkeyvalue /etc.defaults/synoinfo.conf esataportcfg="0"
synosetkeyvalue /etc.defaults/synoinfo.conf internalportcfg="0xffffffffff"
synosetkeyvalue /etc.defaults/synoinfo.conf usbportcfg="0"
synosetkeyvalue /etc.defaults/synoinfo.conf maxdisks=24
```

I wouldn't set esataportcfg="0" if you use an eSATA HDD.
Set maxdisks tothe number of internal drive bays + the number of USB ports you want to appear as internal ports.
